### ISSUE TITLE
Is it possible to hide scroll bar of a code block

### ISSUE THREAD

**Issue by Lesilva** [fiskurgit/MarkdownView#2]
Title says it all. I was trying to see if I can hide the horizontal scroll bar of a code block.

Thanks...

**Comment by fiskurgit** [comment]
Just seen this, far far too late, sorry.

No, this lib is just a wrapper around a JS Markdown parser - all the hard work is delegated to that. Rather than develop this further if I find the time I have an idea for a fully native Android view - just need to find the time to develop it.
